/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  fullReportSidebar: [{type: 'autogenerated', dirName: 'WatershedGoals'}],
  LASidebar: [{type: 'autogenerated', dirName: 'LomaAlta'}],
  BuenaVistaSidebar: [{type: 'autogenerated', dirName: 'BuenaVista'}],
  AguaHediondaSidebar: [{type: 'autogenerated', dirName: 'AguaHedionda'}],
  EncinasSidebar: [{type: 'autogenerated', dirName: 'Encinas'}],
  SanMarcosSidebar: [{type: 'autogenerated', dirName: 'SanMarcos'}],
  EscondidoCreekSidebar: [{type: 'autogenerated', dirName: 'EscondidoCreek'}],
  attachmentsSidebar: [{type: 'autogenerated', dirName: 'Attachments'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
